spring:
  application:
    name: event-management

  data:
    mongodb:
      uri: ${MONGO_URI}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  web:
    error:
      whitelabel:
        enabled: true

server:
  port: ${PORT:8000}

app:
  base-url: http://localhost:${server.port}

  paystack:
    secret-key: ${PAYSTACK_SECRET_KEY:}

  node-env: ${NODE_ENV:development}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}

stripe:
  secret-key: ${STRIPE_SECRET_KEY:}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:}